logging:
  level:
    com.hellozjf.shadowsocks.ssserver: debug
  file: ssserver.log
spring:
  datasource:
    url: jdbc:h2:./ssserver
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 8888
custom:
  min-port: 10000
  max-port: 10100