logging:
  level:
    com.hellozjf.shadowsocks.ssserver: debug
spring:
  datasource:
    url: jdbc:h2:./ssserver
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true