logging:
  level:
    com.hellozjf.shadowsocks.ssserver: debug
  file: ssserver.log
spring:
  datasource:
    url: jdbc:h2:./ssserver
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
server:
  port: 8488