logging:
  level:
    com.hellozjf.shadowsocks.ssserver: info
  file: ssserver.log
spring:
  datasource:
    url: jdbc:mysql://aliyun.hellozjf.com:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zjf@1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  port: 8888
swagger2:
  enable: true
custom:
  min-port: 10000
  max-port: 10101
  # 通过Runtime.exec超时时间，单位秒
  runtime-call-timeout: 2
  # 时区
  timeZone: +08:00